apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sampleapp.fullname" . }}-envoy
  labels:
    app: {{ template "sampleapp.name" . }}
    chart: {{ template "sampleapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: envoy
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: {{ .Values.envoy.containerPort.http.public }}
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: auto
              access_log:
              - name: envoy.file_access_log
                config:
                  path: /dev/stdout
                  format: |
                    {"time":"%START_TIME%","method":"%REQ(:METHOD)%","path":"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%","protocol":"%PROTOCOL%","response_code":%RESPONSE_CODE%,"response_flags":"%RESPONSE_FLAGS%","bytes_received":%BYTES_RECEIVED%,"bytes_sent":%BYTES_SENT%,"duration":%DURATION%,"upstream_service_time":%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%,"x_forwarded_for":"%REQ(X-FORWARDED-FOR)%","user_agent":"%REQ(USER-AGENT)%","request_id":"%REQ(X-REQUEST-ID)%","authority":"%REQ(:AUTHORITY)%","upstream_host":"%UPSTREAM_HOST%"}
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: local_service_http_public
              http_filters:
              - name: envoy.router
                config: {}
      clusters:
      - name: local_service_http_public
        connect_timeout: 0.250s
        type: static
        lb_policy: round_robin
        hosts:
        - socket_address:
            address: 127.0.0.1
            port_value: {{ .Values.sampleapp.containerPort.http.public }}
    admin:
      access_log_path: "/dev/stdout"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: {{ .Values.envoy.containerPort.admin }}